### PR TITLE
Evmosd start failures

### PR DESCRIPTION
**Pull request by khoslaventures**
Doing a bunch of test runs with `evmosd start`

NOTE: basically, every time you start the chain and make genesis file changes, you need to do the folllowing:
```
rm -rf ~/.evmosd
evmosd init testnet --chain-id evmos_9000-2
*copy genesis to config folder*
evmosd start
```
Failure to do so will show you the same error even when changing the genesis.json in the config folder and starting again. The data has to be reset.

### CODE REVIEW

**Comment by khoslaventures** [comment]
Blocked on
```
panic: signature verification failed; please verify account number (0) and chain-id (evmos_9000-2): unauthorized
```

**Comment by artifactstaking** [comment]
panic: pubKey does not match signer address evmos1hsxs04fvxcsqjstvnkvu6p0umfy86lzmsd2hhs with signer index: 0: invalid pubkey

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/genutil.DeliverGenTxs({{0x237b6a8, 0xc00013a020}, {0x23ac1c0, 0xc000111040}, {{0x0, 0x0}, {0xc0000d6d60, 0xc}, 0x0, {0x0, ...}, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.44.3/x/genutil/gentx.go:113 +0x274
github.com/cosmos/cosmos-sdk/x/genutil.InitGenesis(...)
        github.com/cosmos/cosmos-sdk@v0.44.3/x/genutil/genesis.go:18
github.com/cosmos/cosmos-sdk/x/genutil.AppModule.InitGenesis({{}, {_, _}, {_, _}, _, {_, _}}, {{0x237b6a8, 0xc00013a020}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.44.3/x/genutil/module.go:99 +0x15e
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x237b6a8, 0xc00013a020}, {0x23ac1c0, 0xc000111040}, {{0x0, 0x0}, {0xc0000d6d60, 0xc}, 0x0, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.44.3/types/module/module.go:307 +0x29d
github.com/tharsis/evmos/app.(*Evmos).InitChainer(_, {{0x237b6a8, 0xc00013a020}, {0x23ac1c0, 0xc000111040}, {{0x0, 0x0}, {0xc0000d6d60, 0xc}, 0x0, ...}, ...}, ...)
        github.com/tharsis/evmos/app/app.go:605 +0x1d2
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc00105f1e0, {{0x0, 0xed92b2090, 0x0}, {0xc0000d6d60, 0xc}, 0xc0011d4160, {0x33f73f0, 0x0, 0x0}, ...})
        github.com/cosmos/cosmos-sdk@v0.44.3/baseapp/abci.go:62 +0x475
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc001545b00, {{0x0, 0xed92b2090, 0x0}, {0xc0000d6d60, 0xc}, 0xc0011d4160, {0x33f73f0, 0x0, 0x0}, ...})
        github.com/tendermint/tendermint@v0.34.14/abci/client/local_client.go:272 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x3, {{0x0, 0xed92b2090, 0x0}, {0xc0000d6d60, 0xc}, 0xc0011d4160, {0x33f73f0, 0x0, 0x0}, ...})
        github.com/tendermint/tendermint@v0.34.14/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x23091e8, 0x8}}, {0xc0000d6d60, 0xc}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
        github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:319 +0xd98
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0021dd8e8, {0x23ada50, 0xc0011ed450})
        github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x23091e8, 0x8}}, {0xc0000d6d60, 0xc}, 0x1, 0x0, ...}, ...)
        github.com/tendermint/tendermint@v0.34.14/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc00108a280, {0x2354df0, 0xc0010f0c80}, 0xc001010990, {0x2334b80, 0xc00059a600}, 0x0, 0x0, 0xc001010f50, {0x237c518, ...}, ...)
        github.com/tendermint/tendermint@v0.34.14/node/node.go:733 +0x578
github.com/tharsis/ethermint/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x23c08b8, 0xc00105d0b0}, {0x1dbc9fb, 0x7}, {0x2385870, 0xc000e56450}, ...}, ...)
        github.com/tharsis/ethermint@v0.8.0/server/start.go:292 +0xc5f
github.com/tharsis/ethermint/server.StartCmd.func2(0xc000f4ef00, {0x33f73f0, 0x0, 0x0})
        github.com/tharsis/ethermint@v0.8.0/server/start.go:119 +0x228
github.com/spf13/cobra.(*Command).execute(0xc000f4ef00, {0x33f73f0, 0x0, 0x0})
        github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0011bb680)
        github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.2.1/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.2.1/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0, {0xc000deb650, 0x17})
        github.com/cosmos/cosmos-sdk@v0.44.3/server/cmd/execute.go:36 +0x1eb
main.main()
        github.com/tharsis/evmos/cmd/evmosd/main.go:20 +0x38

**Comment by khoslaventures** [comment]
@artifactstaking You will have to do
`evmosd unsafe-reset-all`

and then copy the new genesis over from this PR to `~/.evmosd/config/genesis.json`

Let me know what happens

**Comment by artifactstaking** [comment]
Still get the same error mate

**Comment by nullmames** [comment]
i have the same error, as do many other people. watching this thread

**Comment by artifactstaking** [comment]
just to be clear, we are talking about this genesis file correct?

https://raw.githubusercontent.com/tharsis/testnets/main/olympus_mons/genesis.json

**Comment by nullmames** [comment]
> just to be clear, we are talking about this genesis file correct?
> 
> https://raw.githubusercontent.com/tharsis/testnets/main/olympus_mons/genesis.json

yeah bro!

**Comment by jim3333** [comment]
not work.

**Comment by maxzonder** [comment]
> just to be clear, we are talking about this genesis file correct?
> 
> https://raw.githubusercontent.com/tharsis/testnets/main/olympus_mons/genesis.json

no, to test we should use genesis from this PR, not the one you mentioned

**Comment by maxzonder** [comment]
https://raw.githubusercontent.com/khoslaventures/testnets-1/evmosd-start-failures/olympus_mons/genesis.json

This one. BTW the error is same (panic: signature verification failed; please verify account number (0) and chain-id (evmos_9000-2): unauthorized)

**Comment by khoslaventures** [comment]
To be clear, all the preceding messages indicate this PR doesn't work. No need to repeat the broken signature errors, we got testing to know that 😄

**Pull request closed without merging**
